---
deployment:
  tasks:
    - export DEPLOYPATH=/home/liveservice/public_html/
    - /bin/cp -R * /home/liveservice/
    - /bin/cp -R public_html/* $DEPLOYPATH
    - /bin/cp .htaccess /home/liveservice/
    - /bin/cp public_html/.htaccess $DEPLOYPATH
    - /bin/rm -f $DEPLOYPATH/index.html
    - /bin/chmod -R 775 /home/liveservice/storage /home/liveservice/bootstrap/cache
