---
deployment:
  tasks:
    - export DEPLOYPATH=/home/bestliveiptv/public_html/
    - /bin/cp -R * /home/bestliveiptv/
    - /bin/cp -R public_html/* $DEPLOYPATH
    - /bin/cp .htaccess /home/bestliveiptv/
    - /bin/cp public_html/.htaccess $DEPLOYPATH
    - /bin/chmod -R 775 /home/bestliveiptv/storage /home/bestliveiptv/bootstrap/cache
